### ISSUE TITLE
Missing message.tmpl file when using image v1.2.2 in a kubernetes deployment

### ISSUE THREAD

**Issue by dimitrigraf** [mr-karan/calert#27]
Hi there

First of all: Thanks for this app!

I am currently experiencing an error when updating the deployment to use the image version `1.2.2` instead of `1.0.0-stable`. I use the image in a Kubernetes deployment, just like the one in your `kustomize` folder. 

The error I am getting when using `kubectl logs` is the following:

```
ERR: 2021/05/05 07:32:05 /home/karan/Projects/calert/helper.go:25: Error reading template open message.tmpl: no such file or directory
ERR: 2021/05/05 07:32:05 /home/karan/Projects/calert/main.go:44: Error while processing request: open message.tmpl: no such file or directory
```
The `/ping` healthcheck is working. Everything should be configured correctly, room name, url etc.

With version `1.0.0-stable` everything worked perfectly fine.

Any ideas? Am I missing something in my Kubernetes resources? 

UPDATE:
I was able to get it running by just adding the `message.tmpl` file in the container root `/`. How can bis be fixed in the image?

**Comment by mr-karan** [comment]
Fixed it with https://github.com/mr-karan/calert/releases/tag/v1.2.3

```
$ ls /etc/calert
config.toml   message.tmpl
```

Thanks for reporting this. :)

**Comment by dimitrigraf** [comment]
Hi!

Wow, that was quick! Thanks for the effort. 

I tested it together with my Kubernetes deployment. There the `message.tmpl` file still doesn't appear. I also tested the image directly with `kubectl run`, there the file appears. I guess this is because of the ConfigMap mount specified in the deployment, where the `config.toml` is mounted in `/etc/calert/`. 

Any idea how to fix this? Do I need an additional ConfigMap just for the `message.tmpl`? Or is there a way to not overwrite the folder contents but to add additional files instead?

**Comment by mr-karan** [comment]
Yep, your patch seems correct. The `subPath` is required, so that other files in the directory are not overridden.

> Are you going to update the files in the kustomize folder? There are also some redis related resources there that I don't really understand.

Yep, this seems to be very old, outdated. I've cleaned up the `kustomize` folder: https://github.com/mr-karan/calert/commit/078cfb48f9253ee7f4b994cd02e32dcf392d9735

**Comment by dimitrigraf** [comment]
Cheers! Pleasure working with you :)
